tp_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: TPUserBundle:Default:index }
MDWAnnotations:
    resource: "@TPUserBundle/Controller/"
    prefix:   /
    type:     annotation