tp_user:
    resource: "@TPUserBundle/Resources/config/routing.yml"
    prefix:   /

t_ppedidos:
    resource: "@TPpedidosBundle/Resources/config/routing.yml"
    prefix:   /
    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

