security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:

    providers: 
        chain_provider:
            chain:
                providers: [administrators, in_memory]
        administrators:
            entity: { class: TPUserBundle:User, property: username}        
        in_memory:
            memory:
                users:
                    admin: { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:	^/
            anonymous: ~
            form_login:
                login_path: login
                default_target_path: /pedido/home
            logout:
                path: /logout
                target: /pedido/home
            remember_me:
                key: prueba123
                lifetime: 3600
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/usuario, roles: ROLE_USER }


    encoders:
        TP\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1


    acl:
        connection: default