utn_security_homepage:
    pattern:  admin/hello/{name}
    defaults: { _controller: TPSecurityBundle:Default:index }
login:
    path:   /login
    defaults: { _controller: TPSecurityBundle:Security:login }
login_check:
    path:   /login_check
logout:
    pattern:   /logout
utn_security_cajalogin:
    pattern:  caja
    defaults: { _controller: TPSecurityBundle:Default:cajaLogin }
